version: '3'
services:
  app:
    build: .
    volumes:
      - .:/app
    env_file: .env
    working_dir: /app
    command: bash -c 'php artisan config:clear && php artisan migrate && php artisan serve --host=0.0.0.0 --port=8000'
    depends_on:
      - db
    links:
      - db
    ports:
      - "8000:8000"
  db:
    image: "mysql:5.7.30"
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_DATABASE=task-manager
      - MYSQL_USER=root
      - MYSQL_PASSWORD=pass
